//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InvestmentTrackerEntities : DbContext
    {
        public InvestmentTrackerEntities()
            : base("name=InvestmentTrackerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<earningslab> earningslabs { get; set; }
        public virtual DbSet<investmentschedule> investmentschedules { get; set; }
        public virtual DbSet<investmenttype> investmenttypes { get; set; }
        public virtual DbSet<provider> providers { get; set; }
        public virtual DbSet<useraccountdetail> useraccountdetails { get; set; }
        public virtual DbSet<userslogin> userslogins { get; set; }
    }
}
